//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATM_Machine.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/Bank_Host")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FundsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Funds {
            get {
                return this.FundsField;
            }
            set {
                if ((this.FundsField.Equals(value) != true)) {
                    this.FundsField = value;
                    this.RaisePropertyChanged("Funds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdAccount {
            get {
                return this.IdAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.IdAccountField, value) != true)) {
                    this.IdAccountField = value;
                    this.RaisePropertyChanged("IdAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCard {
            get {
                return this.IdCardField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCardField, value) != true)) {
                    this.IdCardField = value;
                    this.RaisePropertyChanged("IdCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IBankService")]
    public interface IBankService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/DoWork", ReplyAction="http://tempuri.org/IBankService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/LoadProfile", ReplyAction="http://tempuri.org/IBankService/LoadProfileResponse")]
        ATM_Machine.ServiceReference.Account LoadProfile(string idcard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetFunds", ReplyAction="http://tempuri.org/IBankService/GetFundsResponse")]
        bool GetFunds(string idaccount, long funds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/LogIn", ReplyAction="http://tempuri.org/IBankService/LogInResponse")]
        bool LogIn(string idcard, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/CheckAccount", ReplyAction="http://tempuri.org/IBankService/CheckAccountResponse")]
        bool CheckAccount(string idaccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/GetIdAccount", ReplyAction="http://tempuri.org/IBankService/GetIdAccountResponse")]
        string GetIdAccount(string idcard);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankServiceChannel : ATM_Machine.ServiceReference.IBankService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankServiceClient : System.ServiceModel.ClientBase<ATM_Machine.ServiceReference.IBankService>, ATM_Machine.ServiceReference.IBankService {
        
        public BankServiceClient() {
        }
        
        public BankServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public ATM_Machine.ServiceReference.Account LoadProfile(string idcard) {
            return base.Channel.LoadProfile(idcard);
        }
        
        public bool GetFunds(string idaccount, long funds) {
            return base.Channel.GetFunds(idaccount, funds);
        }
        
        public bool LogIn(string idcard, string pin) {
            return base.Channel.LogIn(idcard, pin);
        }
        
        public bool CheckAccount(string idaccount) {
            return base.Channel.CheckAccount(idaccount);
        }
        
        public string GetIdAccount(string idcard) {
            return base.Channel.GetIdAccount(idcard);
        }
    }
}
